apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: hwjs101-hwjsapp
  namespace: hwjs-project
  labels:
    app: hwjsapp
spec:
  selector:
    matchExpressions:
    - key: release
      operator: In
      values:
      - hwjs101
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
